### PR TITLE
Bump Python to 3.10

### PR DESCRIPTION
**Pull request by simoncozens**

### CODE REVIEW

**Review by ThanosPoulakidas — APPROVED** [review]

**Comment by ThanosPoulakidas** [comment]
Thanks a lot @simoncozens! The build phase doesn't show now errors.
Now I have to make the corrections shown here?
image
Because most of the errors I don't think I can understand them

**Comment by simoncozens** [comment]
Well, this is part of learning to be a font engineer. :-) The [Google Fonts Guide](https://googlefonts.github.io/gf-guide/requirements.html) will tell you how to fix some of these. For example, this issue:

```
Checking OS/2 fsType does not impose restrictions.
 fonts/ttf/Geom-Regular.ttf
🔥 FAIL
In this font fsType is set to 4 meaning that: The font may be embedded, and temporarily loaded on the remote system, but documents that use it must not be editable.

No such DRM restrictions can be enabled on the Google Fonts collection, so the fsType field must be set to zero (Installable Embedding) instead. [code: drm]
```

can be fixed by looking at the [Font Embedding (fsType)](https://googlefonts.github.io/gf-guide/requirements.html#font-embedding-fstype) section of the guide. Similarly the expectations for the copyright field are explained [here](https://googlefonts.github.io/gf-guide/requirements.html#font-copyright-and-license); [this page](https://googlefonts.github.io/gf-guide/metrics.html) explains how to set the vertical metrics, and so on.

Start with the FAILS and see how far you can get.

**Comment by ThanosPoulakidas** [comment]
I began with some smaller changes such as the right way of the Copyright and the ascenders and descenders unit etc but during the upload a new problem arose in the build phase again.

Should the program in which I work with, create these problems with the build phase?

**Comment by ThanosPoulakidas** [comment]
I uploaded again the previous working files.

**Comment by ThanosPoulakidas** [comment]
I started making some changes on the files but I think I can't go any further than this for the moment.
Especially the part with copyrights I can't seem to understand what is wrong

**Pull request merged**
